version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_OPTIONS=--max-old-space-size=4096
      - ESBUILD_BINARY_PATH=/usr/local/bin/esbuild
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./services
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./services:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/agenthive
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Optional Ollama service for local LLM support
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  mongodb_data:
  redis_data:
  ollama_data: 