apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tsc-chattsc-vsr
spec:
  host: eae-apis-ENV-REGION.ssc.tsc
  upstreams:
  - name: tsc-chattsc-route
    service: tsc-chattsc-svc
    port: 3000
    client-max-body-size: 30m
  subroutes:
  - path: ~/tsc-chattsc/?(.*)
    action:
      proxy:
        upstream: tsc-chattsc-route
        rewritePath: /$1
        requestHeaders:
          set:
          - name: Host
            value: ${host}
          - name: X-Forwarded-Host
            value: ${host}
          - name: X-Forwarded-Proto
            value: ${scheme}
